# Файл: .gitpod.yml (Исправленная версия)

tasks:
  - name: Setup & Build
    before: |
      echo "Sourcing environment variables..."
      source "$HOME/.cargo/env" || true
      source "$HOME/.bashrc" || true
      echo "Using latest Anchor version..."
      avm use latest
    init: |
      echo "Initial workspace setup and build..."
      anchor build
    command: |
      echo "Starting Solana test validator..."
      solana-test-validator
