tasks:
  - name: Setup & Build
    before: |
      echo "Setting up environment paths explicitly..."
      # Явно добавляем пути к нашим инструментам в PATH.
      export PATH="$HOME/.cargo/bin:$HOME/.local/share/solana/install/active_release/bin:$HOME/.avm/bin:$PATH"
      
      echo "Verifying tool installations..."
      # Проверяем, что команды теперь доступны
      solana --version
      anchor --version

    init: |
      echo "Running initial project build..."
      anchor build
    
    command: |
      echo "Starting Solana test validator..."
      solana-test-validator
