tasks:
  - name: Setup & Build
    # Блок 'before' нам больше не нужен, т.к. .bashrc настроит все автоматически
    init: |
      echo "Verifying tool installations..."
      # Ждем немного, чтобы убедиться, что все инициализировалось
      sleep 5 
      source /home/gitpod/.bashrc
      solana --version
      anchor --version
      echo "Running initial project build..."
      anchor build
    
    command: |
      echo "Starting Solana test validator..."
      # Перед запуском валидатора тоже активируем .bashrc
      source /home/gitpod/.bashrc
      solana-test-validator
