[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
ytk_lock_hook = "8X1TrJV9aW3Sn4ucWXMadVLDB94JMfWM9ya5L9pvPYgC"

[programs.devnet]
ytk_lock_hook = "8X1TrJV9aW3Sn4ucWXMadVLDB94JMfWM9ya5L9pvPYgC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/cl1nt/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"